/**
 * @file sle_job_config.h
 * @brief Route-local configuration for the integrated SLE job receiver.
 */
#ifndef WS63_LASER_RX_UNIFIED_SLE_JOB_CONFIG_H
#define WS63_LASER_RX_UNIFIED_SLE_JOB_CONFIG_H

#define SLE_JOB_DAC_MAX 65535U

#if defined(CONFIG_LASER_RX_WORK_AREA_X_MM)
#define SLE_JOB_GALVO_WORK_AREA_X_MM ((double)CONFIG_LASER_RX_WORK_AREA_X_MM)
#else
#define SLE_JOB_GALVO_WORK_AREA_X_MM 99.0
#endif

#if defined(CONFIG_LASER_RX_WORK_AREA_Y_MM)
#define SLE_JOB_GALVO_WORK_AREA_Y_MM ((double)CONFIG_LASER_RX_WORK_AREA_Y_MM)
#else
#define SLE_JOB_GALVO_WORK_AREA_Y_MM 99.0
#endif

#define SLE_JOB_GALVO_X_MIN_MM 0.0
#define SLE_JOB_GALVO_X_MAX_MM (SLE_JOB_GALVO_WORK_AREA_X_MM)
#define SLE_JOB_GALVO_Y_MIN_MM 0.0
#define SLE_JOB_GALVO_Y_MAX_MM (SLE_JOB_GALVO_WORK_AREA_Y_MM)

#define SLE_JOB_BEILV_X ((double)SLE_JOB_DAC_MAX / SLE_JOB_GALVO_WORK_AREA_X_MM)
#define SLE_JOB_BEILV_Y ((double)SLE_JOB_DAC_MAX / SLE_JOB_GALVO_WORK_AREA_Y_MM)
#define SLE_JOB_STEP_NUM 0.05

#define SLE_JOB_DEFAULT_FEED_RATE 10000.0
#define SLE_JOB_G0_FEED_RATE 100000.0
#define SLE_JOB_MARKING_FEED_RATE_MAX 12000.0
#define SLE_JOB_FRAME_FEED_RATE 500.0
#define SLE_JOB_FRAME_LASER_POWER 200
#define SLE_JOB_LASER_S_MAX 1000.0

#define SLE_JOB_UART_BAUD_RATE 115200
#define SLE_JOB_UART_BUS 1
#define SLE_JOB_UART_TX_PIN 15
#define SLE_JOB_UART_RX_PIN 16

#define SLE_JOB_UART_PIN_MODE 1

#define SLE_JOB_DAC_SPI_BUS 0
#define SLE_JOB_DAC_SPI_CLK_PIN 7
#define SLE_JOB_DAC_SPI_MOSI_PIN 9
#define SLE_JOB_DAC_CS_PIN 10
#define SLE_JOB_DAC_SPI_PIN_MODE 3

#define SLE_JOB_LASER_PWM_CHANNEL 2
#define SLE_JOB_LASER_PWM_GROUP_ID 0
#define SLE_JOB_LASER_PWM_PIN 2
#define SLE_JOB_LASER_PWM_PIN_MODE 1
#define SLE_JOB_LASER_PWM_FREQ_HZ 5000U

#define SLE_JOB_TASK_STACK_SIZE_DEFAULT 0x4000
#define SLE_JOB_TASK_STACK_SIZE_SLE 0x4000
#define SLE_JOB_TASK_PRIO_JOB_UART 3
#define SLE_JOB_TASK_PRIO_SLE 3
#define SLE_JOB_TASK_PRIO_JOB_EXECUTOR 4
#define SLE_JOB_TASK_PRIO_MOTION 4

#define SLE_JOB_MTU_SIZE 512U
#define SLE_JOB_CONN_INTERVAL_18_75MS 0x0FU
#define SLE_JOB_CONN_INTERVAL_UNITS SLE_JOB_CONN_INTERVAL_18_75MS

#define SLE_JOB_MOTION_QUEUE_SIZE 512
#define SLE_JOB_MOTION_QUEUE_OK_WATERMARK 128
#define SLE_JOB_MOTION_WDT_KICK_INTERVAL_US 100000U
#define SLE_JOB_MOTION_SAMPLE_PERIOD_US 1000U

#define SLE_JOB_MOTION_SPEED_PROFILE_STABLE 0
#define SLE_JOB_MOTION_SPEED_PROFILE_FAST 1
#define SLE_JOB_MOTION_SPEED_PROFILE_AGGRESSIVE 2

#ifndef SLE_JOB_MOTION_SPEED_PROFILE
#define SLE_JOB_MOTION_SPEED_PROFILE SLE_JOB_MOTION_SPEED_PROFILE_FAST
#endif

#if SLE_JOB_MOTION_SPEED_PROFILE == SLE_JOB_MOTION_SPEED_PROFILE_STABLE
#define SLE_JOB_MOTION_MIN_MARK_SEGMENT_US 1000U
#elif SLE_JOB_MOTION_SPEED_PROFILE == SLE_JOB_MOTION_SPEED_PROFILE_FAST
#define SLE_JOB_MOTION_MIN_MARK_SEGMENT_US 500U
#elif SLE_JOB_MOTION_SPEED_PROFILE == SLE_JOB_MOTION_SPEED_PROFILE_AGGRESSIVE
#define SLE_JOB_MOTION_MIN_MARK_SEGMENT_US 250U
#else
#error "Unsupported SLE_JOB_MOTION_SPEED_PROFILE"
#endif

#define SLE_JOB_MOTION_END_DRAIN_TIMEOUT_MS 120000U

#if !defined(CONFIG_LASER_RX_SLE_JOB_CACHE_SIZE)
#error "CONFIG_LASER_RX_SLE_JOB_CACHE_SIZE must be defined for the SLE job route"
#endif

#if CONFIG_LASER_RX_SLE_JOB_CACHE_SIZE != 65536
#error "The integrated SLE job route requires a 65536-byte cache"
#endif

#define SLE_JOB_CACHE_SIZE CONFIG_LASER_RX_SLE_JOB_CACHE_SIZE

#define SLE_JOB_DIAG_LOG 0
#define SLE_JOB_DIAG_LOG_MAX_DATA 8U
#define SLE_JOB_TIMING_LOG 1
#define SLE_JOB_TIMING_FIRST_PACKETS 8U
#define SLE_JOB_TIMING_EVERY_PACKETS 32U
#define SLE_JOB_TIMING_SLOW_MS 20U

#define SLE_JOB_TX_DATA_CHUNK_MAX 214U
#define SLE_JOB_TX_ACK_TIMEOUT_MS 1000U
#define SLE_JOB_TX_RETRY_MAX 3U
#define SLE_JOB_TX_UART_RX_BUF_SIZE 4096U
#define SLE_JOB_TX_UART_READ_TIMEOUT_MS 20U
#define SLE_JOB_WRITE_CFM_TIMEOUT_MS 3000U
#define SLE_JOB_STATUS_LOG_PERIOD_LINES 100U
#define SLE_JOB_EXEC_WAIT_DATA_TIMEOUT_MS 10000U

#define SLE_JOB_PREROLL_BYTES_DEFAULT 2048U

#endif /* WS63_LASER_RX_UNIFIED_SLE_JOB_CONFIG_H */
