/**
 * @file sle_job_config.h
 * @brief Route-local configuration for the integrated SLE job receiver.
 */
#ifndef WS63_LASER_RX_UNIFIED_SLE_JOB_CONFIG_H
#define WS63_LASER_RX_UNIFIED_SLE_JOB_CONFIG_H

#define SLE_JOB_DAC_MAX 65535U

#if defined(CONFIG_LASER_RX_WORK_AREA_X_MM)
#define SLE_JOB_GALVO_WORK_AREA_X_MM ((double)CONFIG_LASER_RX_WORK_AREA_X_MM)
#else
#define SLE_JOB_GALVO_WORK_AREA_X_MM 99.0
#endif

#if defined(CONFIG_LASER_RX_WORK_AREA_Y_MM)
#define SLE_JOB_GALVO_WORK_AREA_Y_MM ((double)CONFIG_LASER_RX_WORK_AREA_Y_MM)
#else
#define SLE_JOB_GALVO_WORK_AREA_Y_MM 99.0
#endif

#define SLE_JOB_GALVO_X_MIN_MM 0.0
#define SLE_JOB_GALVO_X_MAX_MM (SLE_JOB_GALVO_WORK_AREA_X_MM)
#define SLE_JOB_GALVO_Y_MIN_MM 0.0
#define SLE_JOB_GALVO_Y_MAX_MM (SLE_JOB_GALVO_WORK_AREA_Y_MM)

#define SLE_JOB_BEILV_X ((double)SLE_JOB_DAC_MAX / SLE_JOB_GALVO_WORK_AREA_X_MM)
#define SLE_JOB_BEILV_Y ((double)SLE_JOB_DAC_MAX / SLE_JOB_GALVO_WORK_AREA_Y_MM)
#define SLE_JOB_STEP_NUM 0.05
#define SLE_JOB_G0_STEP_NUM 0.10
#define SLE_JOB_G0_SETTLE_US 200U

#define SLE_JOB_DEFAULT_FEED_RATE 10000.0
#define SLE_JOB_G0_FEED_RATE 100000.0
#define SLE_JOB_MARKING_FEED_RATE_MAX 12000.0
#define SLE_JOB_FRAME_FEED_RATE 500.0
#define SLE_JOB_FRAME_LASER_POWER 200
#define SLE_JOB_LASER_S_MAX 1000.0

#define SLE_JOB_UART_BAUD_RATE 115200
#define SLE_JOB_UART_BUS 1
#define SLE_JOB_UART_TX_PIN 15
#define SLE_JOB_UART_RX_PIN 16

#define SLE_JOB_UART_PIN_MODE 1

#define SLE_JOB_DAC_SPI_BUS 0
#define SLE_JOB_DAC_SPI_CLK_PIN 7
#define SLE_JOB_DAC_SPI_MOSI_PIN 9
#define SLE_JOB_DAC_CS_PIN 10
#define SLE_JOB_DAC_SPI_PIN_MODE 3
#define SLE_JOB_DAC_RECOVER_ON_ARM 0

#define SLE_JOB_LASER_PWM_CHANNEL 2
#define SLE_JOB_LASER_PWM_GROUP_ID 0
#define SLE_JOB_LASER_PWM_PIN 2
#define SLE_JOB_LASER_PWM_PIN_MODE 1
#define SLE_JOB_LASER_PWM_FREQ_HZ 5000U

#define SLE_JOB_TASK_STACK_SIZE_DEFAULT 0x4000
#define SLE_JOB_TASK_STACK_SIZE_SLE 0x4000
#define SLE_JOB_TASK_PRIO_JOB_UART 3
#define SLE_JOB_TASK_PRIO_SLE 2
#define SLE_JOB_TASK_PRIO_MOTION 4
#define SLE_JOB_TASK_PRIO_JOB_EXECUTOR 5

/* LiteOS uses lower numbers for higher priorities.  The timer-woken motion
 * task must be able to preempt the cache/parser producer instead of waiting
 * for the producer's two-tick (20 ms) same-priority time slice. */
#if SLE_JOB_TASK_PRIO_JOB_EXECUTOR <= SLE_JOB_TASK_PRIO_MOTION
#error "SLE job executor must run below the motion task"
#endif

#define SLE_JOB_MTU_SIZE 512U
#define SLE_JOB_CONN_INTERVAL_UNIT_US 125U
#define SLE_JOB_CONN_INTERVAL_UNITS 0x10U /* 2 ms */
#define SLE_JOB_LINK_DATA_LEN_ENABLE 1
#define SLE_JOB_LINK_DATA_LEN_OCTETS SLE_JOB_MTU_SIZE
#define SLE_JOB_LINK_HIGH_THROUGHPUT_ENABLE 1

#define SLE_JOB_MOTION_QUEUE_SIZE 512
#define SLE_JOB_MOTION_QUEUE_OK_WATERMARK 128
#define SLE_JOB_MOTION_WDT_KICK_INTERVAL_US 100000U
#define SLE_JOB_MOTION_SAMPLE_PERIOD_US 1000U
#define SLE_JOB_MOTION_DELAY_CHUNK_US 100U
#define SLE_JOB_MOTION_SLEEP_THRESHOLD_US 0U
#define SLE_JOB_MOTION_SCHED_RELIEF_INTERVAL 0U
#define SLE_JOB_MOTION_SCHED_RELIEF_MS 0U
#define SLE_JOB_MOTION_TIMER_INDEX 2U
#define SLE_JOB_MOTION_TIMER_IRQ_PRIORITY 2U
#define SLE_JOB_MOTION_TIMER_THRESHOLD_US 200U
#define SLE_JOB_MOTION_TIMER_TAIL_US 35U
#define SLE_JOB_MOTION_TIMER_TIMEOUT_MARGIN_MS 20U
#define SLE_JOB_MOTION_HOLD_ACK_TIMEOUT_MS 500U
#define SLE_JOB_EXEC_HOLD_QUIESCE_TIMEOUT_MS 500U
#define SLE_JOB_MOTION_CATCHUP_MAX_STEPS 1U
#define SLE_JOB_MOTION_MOVE_SLOW_MS 500U
#define SLE_JOB_MOTION_MOVE_SLOW_LOG_ENABLE 0
#define SLE_JOB_MOTION_MOVE_SLOW_LOG_PERIOD_MS 5000U

#define SLE_JOB_MOTION_SPEED_PROFILE_STABLE 0
#define SLE_JOB_MOTION_SPEED_PROFILE_FAST 1
#define SLE_JOB_MOTION_SPEED_PROFILE_AGGRESSIVE 2

#ifndef SLE_JOB_MOTION_SPEED_PROFILE
#define SLE_JOB_MOTION_SPEED_PROFILE SLE_JOB_MOTION_SPEED_PROFILE_FAST
#endif

#if SLE_JOB_MOTION_SPEED_PROFILE == SLE_JOB_MOTION_SPEED_PROFILE_STABLE
#define SLE_JOB_MOTION_MIN_MARK_SEGMENT_US 1000U
#elif SLE_JOB_MOTION_SPEED_PROFILE == SLE_JOB_MOTION_SPEED_PROFILE_FAST
#define SLE_JOB_MOTION_MIN_MARK_SEGMENT_US 500U
#elif SLE_JOB_MOTION_SPEED_PROFILE == SLE_JOB_MOTION_SPEED_PROFILE_AGGRESSIVE
#define SLE_JOB_MOTION_MIN_MARK_SEGMENT_US 250U
#else
#error "Unsupported SLE_JOB_MOTION_SPEED_PROFILE"
#endif

#define SLE_JOB_MOTION_END_DRAIN_TIMEOUT_MS 120000U

#if !defined(CONFIG_LASER_RX_SLE_JOB_CACHE_SIZE)
#error "CONFIG_LASER_RX_SLE_JOB_CACHE_SIZE must be defined for the SLE job route"
#endif

#if CONFIG_LASER_RX_SLE_JOB_CACHE_SIZE != 102400
#error "The integrated SLE job route requires a 102400-byte cache"
#endif

#define SLE_JOB_CACHE_SIZE CONFIG_LASER_RX_SLE_JOB_CACHE_SIZE
#define SLE_JOB_EXEC_PREROLL_CACHE_HEADROOM_BYTES 8192U
#define SLE_JOB_EXEC_PREROLL_MAX_BYTES \
    (SLE_JOB_CACHE_SIZE - SLE_JOB_EXEC_PREROLL_CACHE_HEADROOM_BYTES)

#define SLE_JOB_TIMING_SLOW_MS 50U

#define SLE_JOB_TX_DATA_CHUNK_MAX 300U
#define SLE_JOB_DATA_FAST_CUM_ACK_ENABLE 1
#define SLE_JOB_DATA_FAST_CUM_ACK_BYTES (SLE_JOB_TX_DATA_CHUNK_MAX * 3U)
#define SLE_JOB_DATA_FAST_CUM_ACK_INTERVAL_MS 0U
#define SLE_JOB_TX_ACK_TIMEOUT_MS 1000U
#define SLE_JOB_TX_RETRY_MAX 3U
#define SLE_JOB_TX_UART_RX_BUF_SIZE 4096U
#define SLE_JOB_TX_UART_READ_TIMEOUT_MS 20U
#define SLE_JOB_WRITE_CFM_TIMEOUT_MS 3000U
#define SLE_JOB_STATUS_LOG_PERIOD_LINES 100U
#define SLE_JOB_EXEC_WAIT_DATA_TIMEOUT_MS 10000U

#define SLE_JOB_PREROLL_BYTES_DEFAULT 2048U

#endif /* WS63_LASER_RX_UNIFIED_SLE_JOB_CONFIG_H */
