/**
 * @file config.h
 * @brief Configuration for the WiFi WS63 laser marker sample.
 */
#ifndef LEGACY_WIFI_CONFIG_H
#define LEGACY_WIFI_CONFIG_H

#define LEGACY_WIFI_DAC_MAX 65535U

#if defined(CONFIG_LASER_WIFI_WORK_AREA_X_MM)
#define LEGACY_WIFI_GALVO_WORK_AREA_X_MM ((double)CONFIG_LASER_WIFI_WORK_AREA_X_MM)
#else
#define LEGACY_WIFI_GALVO_WORK_AREA_X_MM 70.0
#endif

#if defined(CONFIG_LASER_WIFI_WORK_AREA_Y_MM)
#define LEGACY_WIFI_GALVO_WORK_AREA_Y_MM ((double)CONFIG_LASER_WIFI_WORK_AREA_Y_MM)
#else
#define LEGACY_WIFI_GALVO_WORK_AREA_Y_MM 70.0
#endif

#define LEGACY_WIFI_GALVO_X_MIN_MM 0.0
#define LEGACY_WIFI_GALVO_X_MAX_MM (LEGACY_WIFI_GALVO_WORK_AREA_X_MM)
#define LEGACY_WIFI_GALVO_Y_MIN_MM 0.0
#define LEGACY_WIFI_GALVO_Y_MAX_MM (LEGACY_WIFI_GALVO_WORK_AREA_Y_MM)

#define LEGACY_WIFI_BEILV_X ((double)LEGACY_WIFI_DAC_MAX / LEGACY_WIFI_GALVO_WORK_AREA_X_MM)
#define LEGACY_WIFI_BEILV_Y ((double)LEGACY_WIFI_DAC_MAX / LEGACY_WIFI_GALVO_WORK_AREA_Y_MM)
#define LEGACY_WIFI_STEP_NUM 0.05

#define LEGACY_WIFI_DEFAULT_FEED_RATE 10000.0
#define LEGACY_WIFI_G0_FEED_RATE 100000.0
#define LEGACY_WIFI_MARKING_FEED_RATE_MAX 8000.0
#define LEGACY_WIFI_FRAME_FEED_RATE 500.0
#define LEGACY_WIFI_FRAME_LASER_POWER 200
#define LEGACY_WIFI_LASER_S_MAX 1000.0

#if defined(CONFIG_LASER_WIFI_STATUS_PERIODIC)
#define LEGACY_WIFI_STATUS_PERIODIC 1
#else
#define LEGACY_WIFI_STATUS_PERIODIC 0
#endif

#if defined(CONFIG_LASER_WIFI_AP_SSID)
#define LEGACY_WIFI_AP_SSID CONFIG_LASER_WIFI_AP_SSID
#else
#define LEGACY_WIFI_AP_SSID "WS63_LASER_WIFI"
#endif

#if defined(CONFIG_LASER_WIFI_AP_PSK)
#define LEGACY_WIFI_AP_PSK CONFIG_LASER_WIFI_AP_PSK
#else
#define LEGACY_WIFI_AP_PSK "12345678"
#endif

#if defined(CONFIG_LASER_WIFI_AP_CHANNEL)
#define LEGACY_WIFI_AP_CHANNEL CONFIG_LASER_WIFI_AP_CHANNEL
#else
#define LEGACY_WIFI_AP_CHANNEL 6
#endif
#define LEGACY_WIFI_AP_HIDDEN_FLAG 1

#if defined(CONFIG_LASER_WIFI_TCP_PORT)
#define LEGACY_WIFI_TCP_PORT CONFIG_LASER_WIFI_TCP_PORT
#else
#define LEGACY_WIFI_TCP_PORT 5000
#endif

#define LEGACY_WIFI_AP_IFNAME "ap0"
#define LEGACY_WIFI_AP_IP_A 192
#define LEGACY_WIFI_AP_IP_B 168
#define LEGACY_WIFI_AP_IP_C 43
#define LEGACY_WIFI_AP_IP_D 1
#define LEGACY_WIFI_AP_GW_D 1
#define LEGACY_WIFI_TCP_BACKLOG 1
#define LEGACY_WIFI_TCP_RX_BUF_SIZE 512
#define LEGACY_WIFI_TCP_SOCK_BUF_SIZE 8192

#define LEGACY_WIFI_STATUS_INTERVAL_MS 200
#define LEGACY_WIFI_ACTIVITY_TIMEOUT_MS 200

#define DAC_SPI_BUS 0
#define DAC_SPI_CLK_PIN 7
#define DAC_SPI_MOSI_PIN 9
#define DAC_CS_PIN 10
#define DAC_SPI_PIN_MODE 3

#define LASER_PWM_CHANNEL 2
#define LASER_PWM_GROUP_ID 0
#define LASER_PWM_PIN 2
#define LASER_PWM_PIN_MODE 1
#define LASER_PWM_FREQ_HZ 5000U

#define LEGACY_WIFI_TASK_STACK_SIZE_DEFAULT 0x4000
#define LEGACY_WIFI_TASK_PRIO_WIFI 3
#define LEGACY_WIFI_TASK_PRIO_MOTION 4
#define LEGACY_WIFI_MOTION_QUEUE_SIZE 512
#define LEGACY_WIFI_MOTION_QUEUE_OK_WATERMARK 16
#define LEGACY_WIFI_MOTION_WDT_KICK_INTERVAL_US 100000U
#define LEGACY_WIFI_MOTION_SAMPLE_PERIOD_US 1000U
#define LEGACY_WIFI_MOTION_MIN_MARK_SEGMENT_US 1000U
#define LEGACY_WIFI_MOTION_END_DRAIN_TIMEOUT_MS 120000U

#endif /* LEGACY_WIFI_CONFIG_H */
