/**
 * @file config.h
 * @brief Configuration for the unified WS63 laser RX skeleton.
 */
#ifndef WS63_LASER_RX_UNIFIED_CONFIG_H
#define WS63_LASER_RX_UNIFIED_CONFIG_H

#define DAC_MAX 65535U

#if defined(CONFIG_LASER_RX_WORK_AREA_X_MM)
#define GALVO_WORK_AREA_X_MM ((double)CONFIG_LASER_RX_WORK_AREA_X_MM)
#else
#define GALVO_WORK_AREA_X_MM 99.0
#endif

#if defined(CONFIG_LASER_RX_WORK_AREA_Y_MM)
#define GALVO_WORK_AREA_Y_MM ((double)CONFIG_LASER_RX_WORK_AREA_Y_MM)
#else
#define GALVO_WORK_AREA_Y_MM 99.0
#endif

#define GALVO_X_MIN_MM 0.0
#define GALVO_X_MAX_MM (GALVO_WORK_AREA_X_MM)
#define GALVO_Y_MIN_MM 0.0
#define GALVO_Y_MAX_MM (GALVO_WORK_AREA_Y_MM)

#define BEILV_X ((double)DAC_MAX / GALVO_WORK_AREA_X_MM)
#define BEILV_Y ((double)DAC_MAX / GALVO_WORK_AREA_Y_MM)
#define STEP_NUM 0.05

#define DEFAULT_FEED_RATE 10000.0
#define G0_FEED_RATE 100000.0
#define MARKING_FEED_RATE_MAX 8000.0
#define FRAME_FEED_RATE 500.0
#define FRAME_LASER_POWER 200
#define LASER_S_MAX 1000.0

#define DAC_SPI_BUS 0
#define DAC_SPI_CLK_PIN 7
#define DAC_SPI_MOSI_PIN 9
#define DAC_CS_PIN 10
#define DAC_SPI_PIN_MODE 3

#define LASER_PWM_CHANNEL 2
#define LASER_PWM_GROUP_ID 0
#define LASER_PWM_PIN 2
#define LASER_PWM_PIN_MODE 1
#define LASER_PWM_FREQ_HZ 5000U

#if defined(CONFIG_LASER_RX_UART_BAUD)
#define RX_UART_BAUD_RATE CONFIG_LASER_RX_UART_BAUD
#else
#define RX_UART_BAUD_RATE 115200
#endif

#define RX_UART_BUS 1
#define RX_UART_TX_PIN 15
#define RX_UART_RX_PIN 16
#define RX_UART_PIN_MODE 1

#define TASK_STACK_SIZE_DEFAULT 0x4000
#define TASK_PRIO_UART 3
#define TASK_PRIO_MOTION 4

#define RX_STREAM_STATUS_PERIODIC 0
#define STATUS_INTERVAL_MS 200
#define ACTIVITY_TIMEOUT_MS 200

#define MOTION_QUEUE_SIZE 512
#define MOTION_QUEUE_OK_WATERMARK 16
#define MOTION_WDT_KICK_INTERVAL_US 100000U
#define MOTION_SAMPLE_PERIOD_US 1000U
#define MOTION_MIN_MARK_SEGMENT_US 1000U
#define MOTION_END_DRAIN_TIMEOUT_MS 120000U

#endif /* WS63_LASER_RX_UNIFIED_CONFIG_H */
