/**
 * @file config.h
 * @brief Configuration for structured SLE job laser marker.
 */
#ifndef WS63_LASER_SLE_JOB_CONFIG_H
#define WS63_LASER_SLE_JOB_CONFIG_H

#define DAC_MAX 65535U

#if defined(CONFIG_LASER_SLE_JOB_WORK_AREA_X_MM)
#define GALVO_WORK_AREA_X_MM ((double)CONFIG_LASER_SLE_JOB_WORK_AREA_X_MM)
#else
#define GALVO_WORK_AREA_X_MM 99.0
#endif

#if defined(CONFIG_LASER_SLE_JOB_WORK_AREA_Y_MM)
#define GALVO_WORK_AREA_Y_MM ((double)CONFIG_LASER_SLE_JOB_WORK_AREA_Y_MM)
#else
#define GALVO_WORK_AREA_Y_MM 99.0
#endif

#define GALVO_X_MIN_MM 0.0
#define GALVO_X_MAX_MM (GALVO_WORK_AREA_X_MM)
#define GALVO_Y_MIN_MM 0.0
#define GALVO_Y_MAX_MM (GALVO_WORK_AREA_Y_MM)

#define BEILV_X ((double)DAC_MAX / GALVO_WORK_AREA_X_MM)
#define BEILV_Y ((double)DAC_MAX / GALVO_WORK_AREA_Y_MM)
#define STEP_NUM 0.05

#define DEFAULT_FEED_RATE 10000.0
#define G0_FEED_RATE 100000.0
#define MARKING_FEED_RATE_MAX 12000.0
#define FRAME_FEED_RATE 500.0
#define FRAME_LASER_POWER 200
#define LASER_S_MAX 1000.0

#if defined(CONFIG_LASER_SLE_JOB_UART_BAUD)
#define UART_BAUD_RATE CONFIG_LASER_SLE_JOB_UART_BAUD
#else
#define UART_BAUD_RATE 115200
#endif

#if defined(CONFIG_LASER_SLE_JOB_UART_BUS)
#define LASER_UART_BUS CONFIG_LASER_SLE_JOB_UART_BUS
#else
#define LASER_UART_BUS 1
#endif

#if defined(CONFIG_LASER_SLE_JOB_UART_TX_PIN)
#define LASER_UART_TX_PIN CONFIG_LASER_SLE_JOB_UART_TX_PIN
#else
#define LASER_UART_TX_PIN 15
#endif

#if defined(CONFIG_LASER_SLE_JOB_UART_RX_PIN)
#define LASER_UART_RX_PIN CONFIG_LASER_SLE_JOB_UART_RX_PIN
#else
#define LASER_UART_RX_PIN 16
#endif

#define LASER_UART_PIN_MODE 1

#define DAC_SPI_BUS 0
#define DAC_SPI_CLK_PIN 7
#define DAC_SPI_MOSI_PIN 9
#define DAC_CS_PIN 10
#define DAC_SPI_PIN_MODE 3

#define LASER_PWM_CHANNEL 2
#define LASER_PWM_GROUP_ID 0
#define LASER_PWM_PIN 2
#define LASER_PWM_PIN_MODE 1
#define LASER_PWM_FREQ_HZ 5000U

#define TASK_STACK_SIZE_DEFAULT 0x4000
#define TASK_STACK_SIZE_SLE 0x4000
#define TASK_PRIO_JOB_UART 3
#define TASK_PRIO_SLE 3
#define TASK_PRIO_JOB_EXECUTOR 4
#define TASK_PRIO_MOTION 4

#define MOTION_QUEUE_SIZE 512
#define MOTION_QUEUE_OK_WATERMARK 16
#define MOTION_WDT_KICK_INTERVAL_US 100000U
#define MOTION_SAMPLE_PERIOD_US 1000U
#define MOTION_MIN_MARK_SEGMENT_US 1000U
#define MOTION_END_DRAIN_TIMEOUT_MS 120000U

#if defined(CONFIG_LASER_SLE_JOB_CACHE_SIZE)
#define JOB_CACHE_SIZE CONFIG_LASER_SLE_JOB_CACHE_SIZE
#else
#define JOB_CACHE_SIZE (100U * 1024U)
#endif

#define JOB_DIAG_LOG 0
#define JOB_DIAG_LOG_MAX_DATA 8U
#define JOB_TX_TIMING_LOG 1
#define JOB_TX_TIMING_FIRST_PACKETS 0U
#define JOB_TX_TIMING_EVERY_PACKETS 0U
#define JOB_TX_TIMING_SLOW_MS 500U
#define JOB_TX_DATA_USE_WRITE_CMD 1
#define JOB_TX_CONTROL_USE_WRITE_CMD 1
#define JOB_TX_DATA_FORCE_REQ_AFTER_PREROLL 0
#define JOB_TX_DATA_ASYNC_AFTER_PREROLL 1
#define JOB_TX_DATA_WINDOW_PACKETS 3U
#define JOB_TX_DATA_WINDOW_STALL_MS 3000U
#define JOB_TX_DATA_WINDOW_POLL_MS 5U
#define JOB_TX_DATA_WINDOW_STATUS_PROBE_ENABLE 1
#define JOB_TX_DATA_STATUS_PROBE_WAIT_MS 300U
#define JOB_TX_DATA_FAST_CUM_ACK_ENABLE 1
#define JOB_TX_STREAM_FINAL_DRAIN_GRACE_MS 300U
#define JOB_TX_DATA_RESUME_GRACE_MS 200U
#define JOB_TX_DATA_UART_IDLE_BUSY_MS 1000U
#define JOB_TX_DATA_UART_IDLE_LOG_MS 1000U
#define JOB_TX_DATA_RETX_IDLE_MS 1500U
#define JOB_TX_DATA_RETX_MAX 2U

#define JOB_SLE_MTU_SIZE 512U
#define JOB_SLE_CONN_INTERVAL_7_5MS 0x06U
#define JOB_SLE_CONN_INTERVAL_12_5MS 0x0AU
#define JOB_SLE_CONN_INTERVAL_17_5MS 0x0EU
#define JOB_SLE_CONN_INTERVAL_18_75MS 0x0FU
#define JOB_SLE_CONN_INTERVAL_20MS 0x10U
#define JOB_SLE_CONN_INTERVAL_VENDOR_SPEED 0x14U
#define JOB_SLE_CONN_INTERVAL_40MS 0x20U
#define JOB_SLE_CONN_INTERVAL_UNITS JOB_SLE_CONN_INTERVAL_20MS
#define JOB_SLE_PANEL_CONN_INTERVAL_UNITS JOB_SLE_CONN_INTERVAL_40MS
#define JOB_SLE_LINK_DATA_LEN_ENABLE 1
#define JOB_SLE_LINK_DATA_LEN_OCTETS JOB_SLE_MTU_SIZE
#define JOB_SLE_LINK_HIGH_THROUGHPUT_ENABLE 1

#define JOB_TX_DATA_CHUNK_MAX 300U
#define JOB_TX_ACK_TIMEOUT_MS 2000U
#define JOB_TX_DATA_ACK_TIMEOUT_MS 2000U
#define JOB_TX_EXEC_START_ACK_TIMEOUT_MS 15000U
#define JOB_TX_ASYNC_DATA_DRAIN_TIMEOUT_MS 15000U
#define JOB_TX_RETRY_MAX 3U
#define JOB_TX_UART_RX_BUF_SIZE 4096U
#define JOB_TX_UART_READ_TIMEOUT_MS 20U
#define JOB_TX_CONNECT_WAIT_MS 8000U
#define JOB_TX_UART_RESYNC_BYTE 0x18U
#define JOB_TX_UART_CONTROL_BYTE 0x19U
#define JOB_TX_UART_CONTROL_EXEC_STOP 'S'
#define JOB_TX_UART_CONTROL_ABORT 'A'
#define JOB_TX_UART_CONTROL_FOCUS_OFF 'F'
#define JOB_TX_UART_CONTROL_EXEC_RESUME 'R'
#define JOB_SLE_WRITE_CFM_TIMEOUT_MS 3000U
#define JOB_STATUS_LOG_PERIOD_LINES 100U

#define JOB_PREROLL_BYTES_DEFAULT 2048U

#endif /* WS63_LASER_SLE_JOB_CONFIG_H */
