/**
 * @file legacy_uart_config.h
 * @brief Configuration for the integrated RX legacy UART route.
 */
#ifndef LEGACY_UART_CONFIG_H
#define LEGACY_UART_CONFIG_H

#define LEGACY_UART_DAC_MAX 65535U

#if defined(CONFIG_LASER_RX_WORK_AREA_X_MM)
#define LEGACY_UART_GALVO_WORK_AREA_X_MM ((double)CONFIG_LASER_RX_WORK_AREA_X_MM)
#else
#define LEGACY_UART_GALVO_WORK_AREA_X_MM 99.0
#endif

#if defined(CONFIG_LASER_RX_WORK_AREA_Y_MM)
#define LEGACY_UART_GALVO_WORK_AREA_Y_MM ((double)CONFIG_LASER_RX_WORK_AREA_Y_MM)
#else
#define LEGACY_UART_GALVO_WORK_AREA_Y_MM 99.0
#endif

#define LEGACY_UART_GALVO_X_MIN_MM 0.0
#define LEGACY_UART_GALVO_X_MAX_MM (LEGACY_UART_GALVO_WORK_AREA_X_MM)
#define LEGACY_UART_GALVO_Y_MIN_MM 0.0
#define LEGACY_UART_GALVO_Y_MAX_MM (LEGACY_UART_GALVO_WORK_AREA_Y_MM)

#define LEGACY_UART_BEILV_X ((double)LEGACY_UART_DAC_MAX / LEGACY_UART_GALVO_WORK_AREA_X_MM)
#define LEGACY_UART_BEILV_Y ((double)LEGACY_UART_DAC_MAX / LEGACY_UART_GALVO_WORK_AREA_Y_MM)
#define LEGACY_UART_STEP_NUM 0.05

#define LEGACY_UART_DEFAULT_FEED_RATE 10000.0
#define LEGACY_UART_G0_FEED_RATE 100000.0
#define LEGACY_UART_MARKING_FEED_RATE_MAX 12000.0
#define LEGACY_UART_FRAME_FEED_RATE 500.0
#define LEGACY_UART_FRAME_LASER_POWER 200
#define LEGACY_UART_LASER_S_MAX 1000.0

#if defined(CONFIG_LASER_RX_UART_BAUD)
#define LEGACY_UART_BAUD_RATE CONFIG_LASER_RX_UART_BAUD
#else
#define LEGACY_UART_BAUD_RATE 115200
#endif

#if defined(CONFIG_LASER_RX_UART_STATUS_PERIODIC)
#define LEGACY_UART_STATUS_PERIODIC 1
#else
#define LEGACY_UART_STATUS_PERIODIC 0
#endif

#define LEGACY_UART_STATUS_INTERVAL_MS 200
#define LEGACY_UART_ACTIVITY_TIMEOUT_MS 200

#define LEGACY_UART_BUS 1
#define LEGACY_UART_TX_PIN 15
#define LEGACY_UART_RX_PIN 16
#define LEGACY_UART_PIN_MODE 1

#define LEGACY_UART_TASK_STACK_SIZE 0x4000
#define LEGACY_UART_TASK_PRIO 3
#define LEGACY_UART_MOTION_TASK_PRIO 4
#define LEGACY_UART_MOTION_QUEUE_SIZE 512
#define LEGACY_UART_MOTION_QUEUE_OK_WATERMARK 16
#define LEGACY_UART_MOTION_WDT_KICK_INTERVAL_US 100000U
#define LEGACY_UART_MOTION_SAMPLE_PERIOD_US 1000U
#define LEGACY_UART_MOTION_MIN_MARK_SEGMENT_US 1000U
#define LEGACY_UART_MOTION_END_DRAIN_TIMEOUT_MS 120000U

#endif /* LEGACY_UART_CONFIG_H */
